services:
  - type: web
    name: currency-converter-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /index.html
